### ISSUE TITLE
README: service account exceeds storage quota

### ISSUE THREAD

**Issue by githubluv** [amdean/motion-notify#16]
I set up motion notify a year ago and its been working well up until about 3 months ago.  I get email notifications and links but the motion notify Gdrive account that I setup has no files at the emailed folder link because the video file upload from all 3 of my raspberry pi camera processors fails.  The test 'on_picture_save' returns 
cam@mypicam:~ **$ sudo /etc/motion-notify/motion-notify.py /etc/motion-notify/motion-notify.cfg /home/cam/test.jpg on_picture_save 123 456 test.jpg**
**_Error: [<HttpError 403 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=resumable&alt=json returned "The user has exceeded their Drive storage quota">]_**
My Google user account Gdrive has 0 bytes of 15GB storage used, as I deleted all the files. The _year-month-dayofmonth_ folders get created, but they are always empty.  I also tried deleting all the 'Recent' files in the motion notify user account where the videos were and should be stored.  There are >10,000 files of ~100MB each in the 'Recent' category of the motion notify user Gdrive. There was no change in the error response.  Shared files seem not to be deleted until all references to them are deleted, according to Gdrive delection acknowledgements. I've deleted all the video files in my personal user Gdrive and the motion notify used Gdrive but the same error persists.
**https://stackoverflow.com/questions/42300271/google-drive-api-service-account-the-user-has-exceeded-their-drive-storage-quot**
addresses the issue.  I've checked the service account and sharing accounts permissions.  the service account and motion notify are both 'Owners', so perhaps this error is referring to storage quota on the service account.  I see no way to view the service account storage from the **https://console.developers.google.com/apis/dashboard?project=myProject**
I deleted the shared folders also, but then the error changes to 
**Error: [Could not find the 303_CR_516_Driveway folder 0B9FLiebSNz7hSzJWUjQzbTRtbHM]**

There should be a way to specify the motion notify user as 'Owner' of the data using the service account as a proxy, but this is refered to as 'hacky'.
**Any suggestions as to how to set this up properly to avoid the quota overrun?**  I am hoping for a simple parameter adjustment, but maybe it required service account deletion and an improved recreation.

Here is another pertinent link, though it takes app domain knowledge to use it:
https://stackoverflow.com/questions/38970938/google-drive-api-v3-trying-to-change-the-ownership-of-files-other-than-docs-she

**Comment by githubluv** [comment]
https://stackoverflow.com/questions/28204149/403-quotaexceeded-error-when-executing-com-google-api-services-drive-drive-files
describes the problem and a solution. No experience here with implementing this.

**Comment by amdean** [comment]
This error occurs when the service account runs out of storage. You'll find that the account that you're using to view the files always shows 0 bytes and there is no way to login to the service account via the Google Drive UI. Even when you delete the files via the UI, they'll still exist in the service account. The only way to remove them is deleting them using the service account.

The only way you can access the service account is via the Google Drive API.

There is some cleanup functionality in Motion Notify that will remove old files from the service account which was added in January this year: https://github.com/amdean/motion-notify/blob/master/actions/GoogleDriveCleanupAction.py

You'll need this in motion-notify.cfg:
[GoogleDriveUploadAction]
file_retention_days=80

[EventActionRules]
on_cron_trigger = GoogleDriveCleanupAction:always

And you can then execute cleanup using a cron or directly using this:
./motion-notify.py motion-notify.cfg None on_cron_trigger 123 456 None

A few things to look out for:
The cleanup looks for files in the service account which have a property like this:
key='source' and value='MotionNotify' and visibility='PRIVATE'
That property is set on any files that were uploaded using the version of Motion Notify that was released in January 2017 so if you're using an older version, it won't find any files to remove. You can remove that from the code if you want to remove some files that were uploaded with an older version. Just be aware that it will then target anything in your service account (not a problem if you're just using that service account for Motion Notify).

The first time you run the cleanup you're going to get a very large response from the call to Google Drive and I have seen some out of memory errors when handling that response - especially on the Raspberry Pi. Setting file_retention_days=365 or something high to reduce the size of the list of files to handle is one option or running it on something with more memory is another option. You can then gradually reduce it once you've removed the older files. At some point I'll add some limitation on the response sizes to handle that better.

Once you've got the existing old files removed it's worth having a daily cron job run to remove anything older than the retention period.

**Comment by githubluv** [comment]
Closed, as solved.

**Comment by angusgreen** [comment]
I've recently installed motion-notify, which works fine, except that the GoogleDriveCleanupAction.py isn't removing old files.  I've tried executing cleanup directly using:

./motion-notify.py motion-notify.cfg None on_cron_trigger 123 456 None

...but it returns a HTTP error:

Error: [<HttpError 400 when requesting https://www.googleapis.com/drive/v2/files?q=properties+has+%7B+key%3D%27source%27+and+value%3D%27MotionNotify%27+and+visibility%3D%27PRIVATE%27+and+modifiedDate%3C%272019-02-08%27&alt=json&maxResults=1000 returned "Invalid query">]

Any help greatly appreciated.

**Comment by alanddddd** [comment]
How exactly to run/call the crontab (what to write in crontab -e) to call the drive cleanup action?

**Comment by amdean** [comment]
@alanddddd  - assuming your install is in /home/pi/motion-notify, this is what you need:
`33 10 * * * /home/pi/motion-notify/motion-notify.py /home/pi/motion-notify/motion-notify.cfg None on_cron_trigger 123 456 None`

A couple of other things to note:
- The key_file in entry motion-notify.cfg needs to be the absolute path to the key file rather than the relative path (default is relative)
- In the EventActionRules section of motion-notify.cfg you need this entry: 
`on_cron_trigger = GoogleDriveCleanupAction:always`
